"""feat: text table and label table

Revision ID: 929734aa6b92
Revises: 
Create Date: 2024-10-17 20:27:39.573887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929734aa6b92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_id'), 'label', ['id'], unique=False)
    op.create_table('text',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_id'), 'text', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_id'), table_name='text')
    op.drop_table('text')
    op.drop_index(op.f('ix_label_id'), table_name='label')
    op.drop_table('label')
    # ### end Alembic commands ###
